# Generated by Django 2.1.1 on 2020-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=264, unique=True)),
                ('last_Name', models.CharField(max_length=264)),
                ('user_email', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
